// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgXsPN6e5AIUHGrNlej8yQJsJNiz8v74',
    appId: '1:231008603096:web:b0a3b3fe9d2bd09b8100ad',
    messagingSenderId: '231008603096',
    projectId: 'firebase-test-jeremiah',
    authDomain: 'fir-test-jeremiah.firebaseapp.com',
    storageBucket: 'firebase-test-jeremiah.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHFvjEuo-Fj5NSbAQeQBMZURXGl_7eL2c',
    appId: '1:231008603096:android:ea3a8893e99a71b18100ad',
    messagingSenderId: '231008603096',
    projectId: 'firebase-test-jeremiah',
    storageBucket: 'firebase-test-jeremiah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgo9ijSQ0F3e05JKvn_ZW1nbx2zjX11ng',
    appId: '1:231008603096:ios:09a781bc3b0f51578100ad',
    messagingSenderId: '231008603096',
    projectId: 'firebase-test-jeremiah',
    storageBucket: 'firebase-test-jeremiah.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgo9ijSQ0F3e05JKvn_ZW1nbx2zjX11ng',
    appId: '1:231008603096:ios:572923438a00ee0e8100ad',
    messagingSenderId: '231008603096',
    projectId: 'firebase-test-jeremiah',
    storageBucket: 'firebase-test-jeremiah.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
